[package]
name = "tokio-book"
version = "0.1.0"
authors = ["Keith Noguchi <keith.noguchi@gmail.com>"]
edition = "2018"

[dependencies]
futures = "^0.3"
tokio = { version = "^0.2", features = ["rt-threaded", "macros", "net", "time"] }
