kind: pipeline
type: docker
name: default
steps:
  - name: format
    image: archlinux/base
    commands:
      - pacman -Sy --noconfirm make gcc pkgconf rustup flatbuffers wabt
      - rustup update stable
      - rustup default stable
      - rustup component add rustfmt
      - make fmt
  - name: lint
    image: archlinux/base
    commands:
      - pacman -Sy --noconfirm make gcc pkgconf rustup flatbuffers wabt grep
      - rustup update stable
      - rustup default stable
      - rustup component add clippy
      - make lint
  - name: test
    image: archlinux/base
    commands:
      - pacman -Sy --noconfirm make gcc pkgconf rustup flatbuffers wabt grep
      - rustup update stable
      - rustup default stable
      - make test
    depends_on:
      - format
      - lint
  - name: document
    image: archlinux/base
    commands:
      - pacman -Sy --noconfirm make gcc pkgconf rustup flatbuffers wabt
      - rustup update stable
      - rustup default stable
      - make doc-all
    depends_on:
      - format
      - lint
  - name: install
    image: archlinux/base
    commands:
      - pacman -Sy --noconfirm make gcc pkgconf rustup flatbuffers wabt
      - rustup update stable
      - rustup default stable
      - make install
    depends_on:
      - test
      - document
