# SPDX-License-Identifier: GPL-2.0
[workspace]

members = [
   "book",
   "style",
   "async",
   "async-std",
   "tokio",
   "list",
   "flatbuf",
   "embedded",
   "wasm",
   "stjepang",
   "crossbeam",
   "mio",
   "kafka",
   "async-task",
   "actix-web",
]
