[package]
name = "hyper-book"
version = "0.1.0"
authors = ["Keith Noguchi <keith.noguchi@gmail.com>"]
edition = "2018"

[dev-dependencies]
futures = "0.3"
hyper = "0.13"
tokio = { version = "0.2", features = ["io-std", "rt-threaded"] }
