[package]
name = "stjepang-blog"
version = "0.1.0"
authors = ["Keith Noguchi <keith.noguchi@gmail.com>"]
edition = "2018"

[dependencies]
async-task = "1"
pin-utils = "0.1.0-alpha"
crossbeam = "0.7"

[dev-dependencies]
futures = "0.3"
async-std = "1"
tokio = "0.2"
