[package]
name = "kafka-book"
version = "0.1.0"
authors = ["Keith Noguchi <keith.noguchi@gmail.com>"]
edition = "2018"

[dependencies]
rdkafka = "0"

[dev-dependencies]
futures-util = "0.3"
tokio = { version = "0.2", features = ["rt-threaded"] }
