[package]
name = "the-book"
version = "0.1.0"
authors = ["Keith Noguchi <keith.noguchi@gmail.com>"]
edition = "2018"

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.1"

[dev-dependencies]
rand = "0.7"
num_cpus = "1"
